/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Framework identity returned from the compiled binary.
 * JS uses this to verify that constants.ts matches the binary.
 */
export interface FrameworkIdentity {
  /** Framework name (e.g. "vista") */
  name: string
  /** Integrity token: hash of all naming constants */
  integrityToken: string
  /** All naming constants for cross-verification */
  urlPrefix: string
  staticChunksPath: string
  mountIdPrefix: string
  rscDataGlobal: string
  clientRefsGlobal: string
  buildIdGlobal: string
  buildDir: string
  sseEndpoint: string
  imageEndpoint: string
}
/**
 * Get the framework identity from the compiled Rust binary.
 * This function returns values that are BAKED INTO the binary at compile time.
 * If someone renames constants.ts but doesn't recompile Rust → tokens won't match.
 */
export declare function getFrameworkIdentity(): FrameworkIdentity
/**
 * Verify that a JS-computed integrity token matches the Rust-compiled one.
 * Returns true if they match (framework is authentic), false if tampered.
 */
export declare function verifyIntegrity(jsToken: string): boolean
/** Check if source code contains 'use client' directive */
export declare function isClientComponent(source: string): boolean
/** Detailed analysis of client directive */
export declare function analyzeClientDirective(source: string): ClientDirectiveInfo
export interface ClientDirectiveInfo {
  isClient: boolean
  directiveLine: number
}
export interface RouteNode {
  segment: string
  kind: string
  indexPath?: string
  layoutPath?: string
  loadingPath?: string
  errorPath?: string
  notFoundPath?: string
  children: Array<RouteNode>
}
export declare function getRouteTree(appDir: string): RouteNode
/** Version of vista-napi */
export declare function version(): string
/**
 * Check if source file has a static metadata export
 * Looks for: `export const metadata` or `export const metadata:`
 */
export declare function hasMetadataExport(source: string): boolean
/**
 * Check if source file has generateMetadata function
 * Looks for: `export function generateMetadata` or `export async function generateMetadata`
 */
export declare function hasGenerateMetadata(source: string): boolean
/** Metadata information extracted from a source file */
export interface MetadataInfo {
  hasStaticMetadata: boolean
  hasGenerateMetadata: boolean
}
/** Analyze source file for metadata exports */
export declare function analyzeMetadata(source: string): MetadataInfo
/** Scanned component info for NAPI */
export interface NapiScannedComponent {
  absolutePath: string
  relativePath: string
  isClient: boolean
  directiveLine: number
  componentType: string
  exports: Array<string>
  clientHooksUsed: Array<string>
  hasMetadata: boolean
  hasGenerateMetadata: boolean
}
/** Server component error for NAPI */
export interface NapiServerComponentError {
  file: string
  message: string
  hooks: Array<string>
}
/** Scan result for NAPI */
export interface NapiScanResult {
  clientComponents: Array<NapiScannedComponent>
  serverComponents: Array<NapiScannedComponent>
  pages: Array<NapiScannedComponent>
  layouts: Array<NapiScannedComponent>
  apiRoutes: Array<NapiScannedComponent>
  errors: Array<NapiServerComponentError>
  totalFiles: number
  scanTimeMs: number
}
/** Scan app directory and classify all components (Rust-powered, blazing fast) */
export declare function rscScanApp(appDir: string): NapiScanResult
/** Client module entry for NAPI */
export interface NapiClientModuleEntry {
  id: string
  path: string
  absolutePath: string
  chunkName: string
  exports: Array<string>
  asyncLoad: boolean
}
/** Client manifest for NAPI */
export interface NapiClientManifest {
  buildId: string
  clientModules: Array<NapiClientModuleEntry>
}
/** Generate client manifest (Rust-powered) */
export declare function rscGenerateClientManifest(appDir: string, buildId: string): NapiClientManifest
/** Route entry for NAPI */
export interface NapiRouteEntry {
  pattern: string
  pagePath: string
  layoutPaths: Array<string>
  loadingPath?: string
  errorPath?: string
  routeType: string
}
/** Server module entry for NAPI */
export interface NapiServerModuleEntry {
  id: string
  path: string
  absolutePath: string
  componentType: string
  hasMetadata: boolean
  hasGenerateMetadata: boolean
}
/** Server manifest for NAPI */
export interface NapiServerManifest {
  buildId: string
  serverModules: Array<NapiServerModuleEntry>
  routes: Array<NapiRouteEntry>
}
/** Generate server manifest (Rust-powered) */
export declare function rscGenerateServerManifest(appDir: string, buildId: string): NapiServerManifest
/** Client reference for NAPI */
export interface NapiClientReference {
  id: string
  mountId: string
  chunkUrl: string
  exportName: string
}
/** Pre-rendered component placeholder */
export interface NapiPrerenderedComponent {
  componentId: string
  placeholderHtml: string
  estimatedHeight: number
}
/** Generate unique mount ID for client component */
export declare function rscGenerateMountId(): string
/** Reset mount ID counter (call at start of each request) */
export declare function rscResetMountCounter(): void
/**
 * Pre-render a client component to extract its structure for zero-CLS placeholders
 * This uses Rust to parse the TSX and generate accurate placeholder HTML
 */
export declare function rscPrerenderComponent(filePath: string): NapiPrerenderedComponent | null
/**
 * Pre-render all client components in an app directory
 * Returns a map of component_id -> placeholder_html
 */
export declare function rscPrerenderAllComponents(appDir: string): Record<string, NapiPrerenderedComponent>
