import type { DocsDocSource } from '../types';

export const renderDeploymentDoc: DocsDocSource = {
  category: 'deployment',
  slug: 'render-deployment',
  title: 'Render Deployment (Recommended)',
  summary:
    'Render is currently the safest production deployment target for Vista apps.',
  order: 2,
  updatedAt: '2026-03-04',
  sections: [
    {
      type: 'quote',
      text: 'Render is currently the recommended production target for Vista.',
    },
    {
      type: 'paragraph',
      text: 'If you are launching now, use Render first. This setup is written for end-users deploying a Vista app directly from project root.',
    },
    {
      type: 'heading',
      level: 2,
      text: 'render.yaml Blueprint',
    },
    {
      type: 'code',
      language: 'yaml',
      title: 'render.yaml',
      code: `services:
  - type: web
    name: my-vista-app
    runtime: node
    region: oregon
    plan: free
    buildCommand: |
      npm install --no-audit --no-fund
      npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
    healthCheckPath: /`,
    },
    {
      type: 'heading',
      level: 2,
      text: 'Why This Works',
    },
    {
      type: 'list',
      items: [
        'Uses normal root-level scripts (`npm run build`, `npm run start`).',
        'Matches default scripts generated by `create-vista-app`.',
        'No internal source-directory commands required.',
      ],
    },
    {
      type: 'heading',
      level: 2,
      text: 'Troubleshooting',
    },
    {
      type: 'list',
      items: [
        'If modules are missing, ensure `npm install` runs in the same project root that contains your `package.json`.',
        'If CSS build fails, verify `postcss`, `postcss-cli`, and `tailwindcss` are installed and committed in lockfile.',
        'If start fails, confirm `build` and `start` scripts exist in your app `package.json`.',
      ],
    },
    {
      type: 'links',
      title: 'Related',
      links: [
        { label: 'Vercel Deployment (Experimental)', href: '/docs/deployment/vercel-deployment' },
        { label: 'Vista Config Reference', href: '/docs/reference/vista-config-reference' },
      ],
    },
  ],
};
